# Generated by Django 3.0.5 on 2020-05-11 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=10)),
                ('flat_vis', models.CharField(max_length=100)),
                ('vehicle_no', models.CharField(blank=True, max_length=100)),
                ('reason', models.CharField(max_length=200)),
                ('vis_time', models.DateTimeField(auto_now_add=True)),
                ('vis_returned_time', models.DateTimeField(blank=True, null=True)),
                ('family', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='outgoing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=10)),
                ('flat', models.CharField(max_length=100)),
                ('vehicle_no', models.CharField(blank=True, max_length=100)),
                ('reason', models.CharField(max_length=200)),
                ('reg', models.DateTimeField(auto_now_add=True)),
                ('cameback', models.DateTimeField(blank=True, null=True)),
                ('corona_positive', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
