# Generated by Django 3.0.5 on 2020-05-21 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_system', '0003_auto_20200521_0506'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='is_in',
            field=models.BooleanField(default=False),
        ),
    ]
