# Generated by Django 3.0.5 on 2020-05-22 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_system', '0004_visitor_is_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='is_in',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='vis_returned_time',
        ),
    ]
