# Generated by Django 3.0.5 on 2020-05-22 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_system', '0006_auto_20200522_0608'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='vis_returned_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
