# Generated by Django 3.0.5 on 2020-05-30 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_system', '0007_visitor_vis_returned_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outgoing',
            name='corona_positive',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='parking_slot',
        ),
        migrations.AddField(
            model_name='outgoing',
            name='corona_screening_positive',
            field=models.BooleanField(default=False),
        ),
    ]
