# Generated by Django 3.0.5 on 2020-05-31 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_system', '0008_auto_20200530_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='vehicle_no',
        ),
    ]
