# Generated by Django 3.0.5 on 2020-05-31 04:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management_system', '0009_remove_visitor_vehicle_no'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='outgoing',
            new_name='Resident',
        ),
    ]
